#!/usr/bin/env bash
set -e;

if ! docker info > /dev/null 2>&1; then
    echo -e "Docker is not running." >&2;
    exit 1;
fi

echo '';
echo '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
echo '┃ 🚀 [1mInitializer for Laravel[0m';
echo '┃ ';
echo '┃ This script will complete the rest of the setup needed to install the';
echo '┃ chosen components into your fresh application. This might require';
echo '┃ downloading Docker containers or requiring packages via composer';
echo '┃ multiple times, so it can take a while to complete.';
echo '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
if [ -t 1 ];
then
    echo '';
    read -n 1 -s -r -p "Press any key to continue";
    echo '';
else
    echo '';
fi

echo '';
echo '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
echo '┃ 🚀 [1mInstall dependencies and set up Laravel Sail[0m';

echo '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';echo '';
echo 'docker run --rm \
    -v "$(pwd)":/opt \
    -w /opt \
    laravelsail/php80-composer:latest \
    bash -c "composer install --ignore-platform-reqs && php -r \"file_exists('\''.env'\'') || copy('\''.env.example'\'', '\''.env'\'');\" && php artisan key:generate --ansi && php artisan sail:install --with=mysql,redis,meilisearch,mailhog"'
docker run --rm \
    -v "$(pwd)":/opt \
    -w /opt \
    laravelsail/php80-composer:latest \
    bash -c "composer install --ignore-platform-reqs && php -r \"file_exists('.env') || copy('.env.example', '.env');\" && php artisan key:generate --ansi && php artisan sail:install --with=mysql,redis,meilisearch,mailhog";

echo '';
echo '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
echo '┃ 🚀 [1mAdjust Permissions[0m';

echo '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';echo '';
echo '    if sudo -n true 2>/dev/null; then
        sudo chown -R $USER: .
    else
        echo -e "Please provide your password so we can make some final adjustments to your application\'\''s permissions."
        echo ""
        sudo chown -R $USER: .
    fi'
    if sudo -n true 2>/dev/null; then
        sudo chown -R $USER: .
    else
        echo -e "Please provide your password so we can make some final adjustments to your application\'s permissions."
        echo ""
        sudo chown -R $USER: .
    fi;

echo '';
echo '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
echo '┃ 🚀 [1mStart Laravel Sail[0m';

echo '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';echo '';
echo './vendor/bin/sail up -d'
./vendor/bin/sail up -d;

echo '';
echo -e '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
echo -e '┃ 🚀 [1mMigrate the database[0m';

echo -e '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';echo '';

echo 'Waiting for database to accept connections...'
attempt=1;
maxAttempts=8;
sleepTime=5;
until ./vendor/bin/sail artisan tinker --execute 'try { DB::statement("select true"); echo("DB ready"); } catch (Throwable $e) { exit(1); }' | grep -q "DB ready" || [ $attempt -eq $maxAttempts ]; do
    echo "Attempt $attempt failed, retrying in ${sleepTime}s...";
    ((attempt=attempt+1));
    sleep $sleepTime;
done

if [ "$attempt" -eq "$maxAttempts" ]; then
    echo "Could not connect to database after $attempt attempts! Aborting...";
fi

echo "Database ready!"
echo './vendor/bin/sail artisan migrate'
./vendor/bin/sail artisan migrate

echo '';
echo '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
echo '┃ 🚀 [1mRun the database seed[0m';

echo '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';echo '';
echo './vendor/bin/sail artisan db:seed'
./vendor/bin/sail artisan db:seed;

echo '';
echo '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
echo '┃ 🚀 [1mSetup frontend[0m';

echo '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';echo '';
echo './vendor/bin/sail npm install'
./vendor/bin/sail npm install;
echo './vendor/bin/sail npm run dev'
./vendor/bin/sail npm run dev;

echo '';
echo '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
echo '┃ 🚀 [1mFixing Directoy and Files Permissions[0m';

echo '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';echo '';
echo 'sudo chmod +x run'
echo sudo chmod +x run;
echo 'sudo chmod 777 -R storage/logs/'
sudo chmod 777 -R storage/logs/;
echo 'sudo chmod 777 -R storage/framework/'
sudo chmod 777 -R storage/framework/;
echo 'sudo chmod 777 -R storage/app/public/profile-photos'
sudo chmod 777 -R storage/app/public/profile-photos;

# Remove TODO in readme
perl -0777 -pi -e 's/<!-- Initializer for Laravel Todos START  -->.*<!-- Initializer for Laravel Todos END  -->//gs' README.md

echo '';
echo '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
echo '┃ 🚀 [1mDone![0m';
echo '┃ ';
echo '┃ You can now have a look at README.md, for further instructions, guides';
echo '┃ and links to the installed components.';
echo '┃ ';
echo '┃ Some helpful links:';
echo '┃ - Your Application http://localhost';
echo '┃ - Preview Emails via Mailhog http://localhost:8025';
echo '┃ - MeiliSearch Administration Panel http://localhost:7700';
echo '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';echo '';
