#!/usr/bin/env bash
# Description: Script to receive a command to run
# Example: ./run "composer -v"
echo "🚀 Running $1..."

docker run --rm \
    -v "$(pwd)":/opt \
    -w /opt \
    laravelsail/php80-composer:latest \
    bash -c "$1";
